Capstone Task 23/lunasoul/base/urls.py
from django.urls import path, include
from . import views

app_name = 'base'

urlpatterns = [
    path('', views.index, name='index'),
]

Capstone Task 23/lunasoul/blog/urls.py
from django.views.generic import ListView, DetailView
from .models import Post
from django.urls import path, include
from . import views

from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:pk>/', views.post_detail, name='post_detail'),
]

Capstone Task 23/lunasoul/lunasoul/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', include('base.urls')),
    path('registration/', include('registration.urls')),
    path('merch/', include('merch.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Capstone Task 23/lunasoul/merch/urls.py
from django.urls import path, include
from . import views
from django.shortcuts import render

app_name = 'merch'

urlpatterns = [
    path('', views.shop, name='shop'),
]

Capstone Task 23/lunasoul/registration/urls.py
from . import views
from django.urls import path
from registration.views import register

app_name = 'registration'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
]

Capstone Task 23/lunasoul/base/models.py
from django.db import models

# Create your models here.

Capstone Task 23/lunasoul/blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

Capstone Task 23/lunasoul/merch/models.py
from django.db import models

# Create your models here.

Capstone Task 23/lunasoul/base/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

Capstone Task 23/lunasoul/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

def post_list(request):
    posts = Post.objects.all()
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})

Capstone Task 23/lunasoul/merch/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def shop(request):
    return render(request, 'shop.html')

Capstone Task 23/lunasoul/base/templates/index.html
{% load static %}

<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title> Rock & Roll  </title>
</head>
<body>
{% include 'navigation.html' %}

  <!-- Welcome Banner -->
  <header class="jumbotron text-center">
    <div class="container">
      <h1 style="color:Tomato;"> Adrenaline </h1>
        <br>
      <p style="font-size: 40px;">Our album <span style="font-weight: bold; color: #d2184e;">GO CRAZY </span> releases September 1st<p>
        <p>Make sure you download it because it will Blow your mind</p>
    </div>
  </header>

  <!-- Band Picture section -->
  <section class="container text-center">
    <img src="{% static 'img/download1.jpg' %}" alt="Band Image" class="img-fluid">
  </section>

  <!-- About section -->
  <section class="container">
    <h2 style="color:Tomato;"> About Us</h2>
   <p>We are South Africas next big hit, Adrenaline. Our journey began when we auditioned for the TV talent contest SA got Talent <p/>
    <p>It was so nerve wracking sitting back stage hearing everyone with such awesome voices. As the competition went on we got to know each other and really support each others journey.</p>
    <p>When the judges suggest we get put in a group it was like obviously, why didn't we think of that. It was just the natural thing to do.</p>
    <p>We are like best friends now and it's so much fun getting to travel the world together and do what we love. Come see us on tour, and tweet us which city we should visit next!</p>

    <p> ITS NOT MUSIC ITS ADRENALINE # </p>

    <!-- Music section -->
  <section class="container">
    <h2 style="color:Tomato;"> Our Music</h2>
      <p>We want our sound to be like the beattles with a cool hip hop and funky vibes. Like we just want it to feel really energetic with an attitude.<p/>
      <p>So far we have released the album <span style="font-weight: bold; text-size: 60px; color: #0d755b">Bullet to the brain</span> which went double platinum.</p>
      <p>Our next album,  <span style="font-weight: bold; color: #d2184e;"> GO CRAZY </span>, is out September 1st. You can preorder it where-ever music is sold.</p>

Capstone Task 23/lunasoul/base/templates/navigation.html
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Anton&family=Permanent+Marker&display=swap');

    body {
      background-color: #f0e6fc;
    }

    .navbar {
      background-color: #5c18d2;
    }

    h1 {
    font-family: 'Permanent Marker', cursive;
    font-size: 100px;
    color: #5c18d2;
    text-shadow: 2px 2px 4px #f5c7d1;
    }

    h2, h3 {
      font-family: 'Anton', sans-serif;
      font-size: 60px;
      color: #5c18d2;
    }

    .jumbotron {
      background-color: #d7caed;
    }

    .card {
      background-color: #d7caed;
    }

    .btn-primary {
      background-color: #bea1f0;
      border-color: #f5c7d1;
    }

    .btn-primary:hover {
      background-color: #5c18d2;
      border-color: #ad1444;
    }

    p {
      font-family: 'Karla', sans-serif;
      font-size: 30px;
    }
  </style>

<!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'base:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:post_list' %}">Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'registration:register' %}">Join</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'merch:shop' %}">Merch (MEMBER ACCESS ONLY)</a>
        </li>
      </ul>
    </div>
  </nav>

Capstone Task 23/lunasoul/blog/templates/blog/navigation.html
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <style>
    @import url("https://fonts.googleapis.com/css2?family=Lilita+One&display=swap");
    @import url("https://fonts.googleapis.com/css2?family=Karla:wght@200&display=swap");

    body {
      background-color: #f8e9ed;
    }

    .navbar {
      background-color: #d2184e;
    }

    h1 {
    font-family: "Lilita One", cursive;
    font-size: 100px;
    color: #d2184e;
    text-shadow: 2px 2px 4px #f5c7d1;
    }

    h2, h3 {
      font-family: 'Karla', ExtraBold 800;
      font-size: 60px;
      color: #d2184e;
    }

    .jumbotron {
      background-color: #ffd7e5;
    }

    .card {
      background-color: #ffeff3;
    }

    .btn-primary {
      background-color: #d2184e;
      border-color: #d2184e;
    }

    .btn-primary:hover {
      background-color: #ad1444;
      border-color: #ad1444;
    }

    p {
      font-family: 'Karla', sans-serif;
      font-size: 30px;
    }
  </style>
<!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'base:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:post_list' %}">Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'registration:register' %}">Join</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'merch:shop' %}">Merch (MEMBER ACCESS ONLY)</a>
        </li>
      </ul>
    </div>
  </nav>

Capstone Task 23/lunasoul/blog/templates/blog/post_detail.html
{% include 'navigation.html' %}
<h2 style="color: cornflowerblue; font-family: 'Karla', cursive; font-size: 80px; font-weight: bold;">{{ post.title }}</h2>
<p>{{ post.content }}</p>
<h2 style="color: cornflowerblue; font-family: 'Karla', cursive; font-size: 50px; font-weight: bold; text-align: center;">XOXO Adrenaline </h2>                                         XOXO Adarenaline</h2>
<p>Created at: {{ post.created_at }}</p>

Capstone Task 23/lunasoul/blog/templates/blog/post_list.html
{% include 'navigation.html' %}
<h1 style="color:Tomato;"> Blog Posts </h1>
{% for post in posts %}
    <p style="color: cornflowerblue; font-family: 'Karla', cursive; font-size: 50px; font-weight: bold;"><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></p>
    <p>Created at: {{ post.created_at }}</p>
    <br>
{% endfor %}

Capstone Task 23/lunasoul/merch/templates/navigation.html
*+  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <style>
    @import url("https://fonts.googleapis.com/css2?family=Lilita+One&display=swap");
    @import url("https://fonts.googleapis.com/css2?family=Karla:wght@200&display=swap");

    body {
      background-color: #f8e9ed;
    }

    .navbar {
      background-color: #d2184e;
    }

    h1 {
    font-family: "Lilita One", cursive;
    font-size: 100px;
    color: #d2184e;
    text-shadow: 2px 2px 4px #f5c7d1;
    }

    h2, h3 {
      font-family: 'Karla', ExtraBold 800;
      font-size: 60px;
      color: #d2184e;
    }

    .jumbotron {
      background-color: #ffd7e5;
    }

    .card {
      background-color: #ffeff3;
    }

    .btn-primary {
      background-color: #d2184e;
      border-color: #d2184e;
    }

    .btn-primary:hover {
      background-color: #ad1444;
      border-color: #ad1444;
    }

    p {
      font-family: 'Karla', sans-serif;
      font-size: 30px;
    }
  </style>
<!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'base:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:post_list' %}">Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'registration:register' %}">Join</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'merch:shop' %}">Merch (MEMBER ACCESS ONLY)</a>
        </li>
      </ul>
    </div>
  </nav>

Capstone Task 23/lunasoul/merch/templates/shop.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Merchandise</title>

  <!-- Bootstrap CSS -->
  <!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">

  <style>
    body {
      background-color: #f8e9ed;
    }

    .navbar {
      background-color: #d2184e;
    }

    h1, h2, h3 {
      color: #d2184e;
      text-shadow: 2px 2px 4px #f5c7d1;
    }

    .jumbotron {
      background-color: #ffd7e5;
    }

    .card {
      background-color: #ffeff3;
    }

    .btn-primary {
      background-color: #d2184e;
      border-color: #d2184e;
    }

    .btn-primary:hover {
      background-color: #ad1444;
      border-color: #ad1444;
    }

    /* Additional styles for merchandise page */
    .merchandise {
      padding: 30px;
    }

    .product {
      margin-bottom: 30px;
    }

    .product img {
      width: 100%;
      max-width: 300px;
    }

    .product-title {
      font-size: 20px;
      font-weight: bold;
      margin-top: 10px;
      margin-bottom: 5px;
    }

    .product-price {
      color: #ad1444;
      font-size: 18px;
      font-weight: bold;
    }
  </style>-->
</head>
<body>
  <!-- Navigation -->
{% include 'navigation.html' %}

  <!-- Page Content -->
<html>
  <head>
    <title>Shop Merch</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        .card-img-top {
          object-fit: contain;
          height: 200px;
        }

        .card-img-top:hover {
          transform: scale(1.1);
        }

      </style>
  </head>
  <body>
    <header>

        <div>
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Shop Merch Now & Get 10% off your first purchase !!!</h1>
            </div>
        </div>
    </header>
    <br>
      <div class="row">
        <div class="col-md-6 col-lg-6">
          <div class="card mb-3" style="background-color: white;">
            <br>
            <img src="{% static 'img/54.jpg' %} " class="card-img-top img-fluid" alt="Item 3">
            <div class="card-body">
              <h5 class="card-title">Masks</h5>
              <p class="card-text">R20</p>
              <a href="#" class="btn btn-primary">Buy Now</a>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-6">
          <div class="card mb-3" style="background-color: white;">
            <br>
            <img src="{% static 'img/78.jpg' %} " class="card-img-top img-fluid" alt="Item 4">
            <div class="card-body">
              <h5 class="card-title">custom made ring</h5>
              <p class="card-text">R500</p>
              <a href="#" class="btn btn-primary">Buy Now</a>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 col-lg-6">
          <div class="card mb-3" style="background-color: white;">
            <br>
            <img src="{% static 'img/OIP (1).jpg' %} " class="card-img-top img-fluid">
            <div class="card-body">
              <h5 class="card-title">Mug</h5>
              <p class="card-text">R35</p>
              <a href="#" class="btn btn-primary">Buy Now</a>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-6">
            <div class="card mb-3" style="background-color: white;">
              <br>
              <img src="{% static 'img/OIP.jpg' %} " class="card-img-top img-fluid">
              <div class="card-body">
                <h5 class="card-title">Limited Edition T-Shirt</h5>
                <p class="card-text">R50</p>
                <a href="#" class="btn btn-primary">Buy Now</a>
              </div>
            </div>
          </div>
        </div>

    </body>
    </html>
      <!-- Bootstrap JavaScript
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script> -->
    </body>
  </html>